dist: bionic
language: node_js
node_js:
  - 12

before_script:
  - npm install
  - npm run eslint

script:
  - npm run build
  # - if [ "$TRAVIS_BRANCH" = "master" ]; then ...; fi

branches:
  only:
    - master
    - develop
